name: money2
version: 3.3.4
homepage: https://money2.onepub.dev
documentation: https://money2.onepub.dev
description: Money and Currency classes with fixed precision maths, parsing and
  formatting. (Money.parse('$2010.00') * 10).format('S CC#,##0') -> $ US20,100
repository: https://github.com/onepub-dev/money.dart
environment:
  sdk: '>=2.14.0 <3.0.0'
dependencies:
  decimal: ^2.3.0

  fixed:
    git: 
      url: https://github.com/kopianan/fixed.git
  intl: ^0.18.0
  meta: ^1.8.0
dev_dependencies:
  lint_hard: ^1.0.0
  test: ^1.17.10
dependency_overrides: null

  # path: ../fixed
