name: money
description: >
  Dart implementation of Fowler's Money pattern
version: 0.1.5
author: Roman Shamritskiy <roman@litgroup.ru>
homepage: https://github.com/litgroup/money.dart
environment:
  sdk: ">=1.16.0 <2.0.0"
dev_dependencies:
  test: ">=0.12.14 <0.13.0"
  mockito: ">=1.0.0 <2.0.0"
  coverage: any
  dart_style: any
  dart_dev: any
