name: money2
version: 2.2.0
homepage: https://www.noojee.dev
documentation: https://money2.noojee.dev
description: Money and Currency classes with fixed precision maths, parsing and formating. (Money.parse('$2010.00') * 10).format('S CC#,##0') -> $ US20,100
repository: https://github.com/noojee/money.dart
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  intl: ^0.17.0
  meta: ^1.3.0
dev_dependencies: 
  lint: ^1.0.0
  test: 1.16.0
